spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 50MB        # 单个文件最大大小
      max-request-size: 500MB    # 整个请求最大大小
      enabled: true
minio:
  endpoint: http://47.122.130.122:9000
  accessKey: wenxin
  secretKey: wenxin1114
  bucket: grocery
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081
jwt:
  secret: grocery-wenxin