spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grocery?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&tinyInt1isBit=false&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrlInLocalInfile=true&allowPublicKeyRetrieval=true&allowMultiQueries=true&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrlInLocalInfile=true&
    username: root
    password: root